apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: icr-scan
spec:
  description: >-
    Expects an Snapshot deployed.
  params:
    - name: SNAPSHOT
      description: The json string of the Snapshot under test 
    - default: 'default'
      name: NAMESPACE
      description: Namespace of the application under test
  steps:
    - image: docker.io/openrefactory/icr-unified-engine:latest

      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: NAMESPACE
          value: $(params.NAMESPACE)

      script: |
        echo $(echo -n ${SNAPSHOT} | jq -r .components[0].source.git.url)
        echo $(echo -n ${SNAPSHOT} | jq -r .components[0].source.git.revision)        