apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: icr-scan
spec:
  description: >-
    Expects an Snapshot deployed.

  params:
    - name: SNAPSHOT
      description: The json string of the Snapshot under test 
    
    - default: 'default'
      name: NAMESPACE
      description: Namespace of the application under test
    
    - name: ICR_SECRET
      description: Name of secret which contains Snyk token.
      default: icr-secret

  volumes:
    - name: icr-secret
      secret:
        secretName: $(params.ICR_SECRET)
        optional: true 

  steps:
    - image: docker.io/openrefactory/icr-unified-engine:latest
      
      volumeMounts:
        - name: icr-secret
          mountPath: "/etc/secrets"
          readOnly: true

      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: NAMESPACE
          value: $(params.NAMESPACE)

      script: |
        LICENSE_KEY_FILE="/etc/secrets/LICENSE_KEY"
        CONFIG_FILE="config"

        # Read the license key content
        LICENSE_KEY_CONTENT=$(cat "$LICENSE_KEY_FILE")

        echo "$LICENSE_KEY_CONTENT"  

        # Append "LICENSE_KEY" and the content of the license key file to the config file on the same line
        echo "LICENSE_KEY $LICENSE_KEY_CONTENT" >> "$CONFIG_FILE"
        echo "" >> "$CONFIG_FILE"
        echo "String has been appended to $CONFIG_FILE"
        cat "$CONFIG_FILE"
        echo "SARIF /workspaceOR/results/sarif/" >> "$CONFIG_FILE"
        echo "GOPATH /workspaceOR/GP/" >> "$CONFIG_FILE"
        echo "SUMMARIES_PATH /workspaceOR/summaries/" >> "$CONFIG_FILE"

        sh configure_run.sh --engine=Go --git_url=$(echo -n ${SNAPSHOT} | jq -r .components[0].source.git.url) --commit_hash=$(echo -n ${SNAPSHOT} | jq -r .components[0].source.git.revision)
        cd /workspaceOR/results/sarif/ || { echo "Directory not found"; exit 1; }
        for file in *.json; do
          echo "Pretty printing $file:"
          jq '.' "$file"
        done