apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: icr-scan
spec:
  description: >-
    Expects an Snapshot deployed.

  params:
    - name: SNAPSHOT
      description: The json string of the Snapshot under test 
    
    - default: 'default'
      name: NAMESPACE
      description: Namespace of the application under test
    
    - name: ICR_SECRET
      description: Name of secret which contains Snyk token.
      default: icr-secret

  volumes:
    - name: icr-secret
      secret:
        secretName: $(params.ICR_SECRET)
        optional: true 

  steps:
    - image: docker.io/openrefactory/icr-unified-engine:latest
      
      volumeMounts:
        - name: icr-secret
          mountPath: "/etc/secrets"
          readOnly: true

      env:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: NAMESPACE
          value: $(params.NAMESPACE)

      script: |
        cat /etc/secrets/LICENSE_KEY && echo >> config
        echo "SARIF /workspaceOR/results/sarif/" >> config
        echo "GOPATH /workspaceOR/GP/" >> config
        echo "SUMMARIES_PATH /workspaceOR/summaries/" >> config
        sh configure_run.sh --engine=Go --git_url=$(echo -n ${SNAPSHOT} | jq -r .components[0].source.git.url) --revision=$(echo -n ${SNAPSHOT} | jq -r .components[0].source.git.revision)
        cd /workspaceOR/results/sarif/ || { echo "Directory not found"; exit 1; }
        for file in *.json; do
          echo "Pretty printing $file:"
          jq '.' "$file"
        done